grpc:
  port: 50051
db:
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    port: 5432
    username: "your_username"
    password: "your_password"
    db_name: "your_db_name"
    conn:
      min: 1
      max: 2